Add default callback setting
utopia-rise/fmod-gdnative pull request #136
Opened 2022-09-27 04:09 UTC by CedNaru

fix #129

2022-09-27 11:14 UTC, piiertho commented on src/godot_fmod.h
> +        void setCallback(uint64_t instanceId, int callbackMask);
standard is snake_case

2022-09-27 15:29 UTC, piiertho requested changes

2022-09-27 15:29 UTC, piiertho commented on src/godot_fmod.h
> +        void set_desc_callback(String eventPath, int callbackMask);
```cpp
void set_desc_callback(const String& eventPath, int callbackMask);
```

2022-10-08 05:41 UTC, bitbrain commented
Let me ensure to include this in #123 as well

2022-11-11 14:17 UTC, piiertho approved these changes

2022-11-11 14:47 UTC, merged