Change Object to Node and add additional type check.
utopia-rise/fmod-gdnative pull request #63
Opened 2021-01-24 06:45 UTC by CedNaru

Fix issue #60 

All exposed methods that previously used Object are now using Node as parameter/return type.
The node has to be either be a CanvasItem or a spatial, otherwise, an error is returned.

2021-01-24 06:54 UTC, CedNaru commented
Added another condition. The node has to be in the scene_tree otherwise getting the transform will cause an error.

2021-01-24 14:36 UTC, piiertho requested changes
Only few comments to improve the existing codebase.

2021-01-24 14:36 UTC, piiertho commented on src/godot_fmod.cpp
> +        if (s != nullptr) {
Those two line can be replaced with:
```cpp
if (auto* s{Node::cast_to<Spatial>(node)}) ...
```

2021-01-24 14:36 UTC, piiertho commented on src/godot_fmod.cpp
>          if (ci != nullptr) {
same here btw

2021-01-24 14:36 UTC, piiertho commented on src/godot_fmod.cpp
> +        Node *node = listener->gameObj;
I'd like to use cpp 11 init now, even if the former code does not use it, so that we have less things to clean later.

2021-01-24 14:36 UTC, piiertho commented on src/godot_fmod.cpp
> +        if (s != nullptr) {
same here

2021-01-24 14:36 UTC, piiertho commented on src/godot_fmod.cpp
> +        if (!node) {
same here

2021-01-24 14:36 UTC, piiertho commented on src/godot_fmod.h
> +        Node * getObjectAttachedToListener(int index);
Is this formatting wanted ?

2021-01-25 13:49 UTC, piiertho approved these changes
Thx !

2021-01-25 18:43 UTC, merged